version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  flask:
    build: ./flask
    container_name: flask
    volumes:
      - .:/flask
      - ./shared-data:/shared-data
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - postgresql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - flask
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgresql-data:
  shared-data:
