FROM python:3.11.4-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /flask

COPY requirements.txt /flask/

RUN apt-get update && apt-get install -y libpq-dev gcc 

RUN pip install --no-cache-dir -r requirements.txt

COPY . /flask/

CMD ["python", "/flask/flask/app.py", "--bind", "0.0.0.0:8000"]

CMD ["python", "/flask/flask/app.py", "--bind", "0.0.0.0:8000"]

CMD ["python", "/flask/flask/app.py", "--bind", "0.0.0.0:8000"]


# CMD ["tail", "-f", "/dev/null"]