FROM python:3.11.4-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /flask

COPY requirements.txt /flask/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /flask/

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
