
FROM python:3.11.4-slim-buster


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /webscraping

COPY requirements.txt /webscraping/

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . /webscraping/